# Generated by Django 6.0.4 on 2026-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('category', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite'), ('Deluxe', 'Deluxe')], max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
